.\" .TH NRD "8" "LANL HPC" "Jan 2020" "LANL HPC"
.Dd January 30, 2020
.Dt NRD 8
.Dm test
.Os
.Sh NAME
.Nm nrd
.Nd Neighborless Route Detection 
.Sh SYNOPSIS
.Nm
.Op Fl notify 
.Op Fl up
.Op Fl nojoin
.Op Fl dry
.Op Fl force
.Op Fl noclean
.Op Fl conf Ar path
.Op Fl log Ar level
.Op Fl version
.Op Fl help

.Sh DESCRIPTION
NRD can manage ECMP/MultiPath routes on a network by listening to OSPF hello packets.
.Pp
The NRD command takes the following options:
.Bl -tag -width indent
.It Ic -conf Ar file
configuration file to use (default "/etc/nrd.yml")
.It Ic -dry
dryrun, don't actually set routes (default: false)
.It Ic -force
force nrd to control routes even if they already exist (default: false)
.It Ic -iface Ar interface
interface to listen on (default "eth0")
.It Ic -log Ar level
set the log level [0-3] (default: 2)
.It Ic -noclean
don't cleanup managed routes on exit (default: false)
.It Ic -nojoin 
don't join multicast, assume it's already joined (default: false)
.It Ic -notify
send sd_notify messages (default: false)
.It Ic -up
set startup state of routes to up (default: false)
.It Ic -version
output version information and exit

.Sh EXAMPLES
.nf
In the following example, nrd runs on interface "eth1."
.br
We see in the output that nrd automatically discovers the two known routes to be up.

\& [vagrant@leaf1 ~]$ sudo ./nrd -iface eth1 -log 2
\& 2020/01/25 04:30:26 INFO:starting NRD
\& 2020/01/25 04:30:26 INFO:reading config file at: nrd.yml
\& 2020/01/25 04:30:26 INFO:using interface eth1
\& 2020/01/25 04:30:26 INFO:managing route 192.168.57.0/24
\& 2020/01/25 04:30:26 INFO:added router 192.168.56.10
\& 2020/01/25 04:30:26 INFO:added router 192.168.56.11
\& 2020/01/25 04:30:26 INFO:joined multicast group: 224.0.0.5
\& 2020/01/25 04:30:32 INFO:router returned to service 192.168.56.10
\& 2020/01/25 04:30:32 INFO:router 192.168.56.10 is now up
\& 2020/01/25 04:30:32 INFO:route 192.168.57.0/24 is down
\& 2020/01/25 04:30:32 INFO:there are 1 routers up
\& 2020/01/25 04:30:32 INFO:router returned to service 192.168.56.11
\& 2020/01/25 04:30:32 INFO:router 192.168.56.11 is now up
\& 2020/01/25 04:30:32 INFO:updated route 192.168.57.0/24
\& 2020/01/25 04:30:32 INFO:there are 2 routers up
.fi

.Sh AUTHOR
Written by J. Lowell Wofford and Brett Holman.

.Sh "REPORTING BUGS"
.br
Please report bugs on the 
.Nm
home page: <https://github.org/hpc/nrd>

.Sh COPYRIGHT
This software is open source software available under the BSD-3 license.
.br
Copyright (c) 2020, Triad National Security, LLC
.br
See LICENSE file for details.

